//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string NameProduct { get; set; }
        public string TypeOr { get; set; }
        public string YearVolumeRelease { get; set; }
        public int IDMaterial { get; set; }
        public int IDCompany { get; set; }
        public int IDSpecification { get; set; }
        public string Comment { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Material Material { get; set; }
        public virtual Specification Specification { get; set; }
    }
}
