//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocolateFabricApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesAndProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeesAndProduct()
        {
            this.MainTable = new HashSet<MainTable>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDEmployees { get; set; }
        public Nullable<int> IDFinishedProducts { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual FinishedProducts FinishedProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTable> MainTable { get; set; }
    }
}
