//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocolateFabricApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.EmployeesAndProduct = new HashSet<EmployeesAndProduct>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Age { get; set; }
        public Nullable<int> IDGender { get; set; }
        public Nullable<int> IDPost { get; set; }
        public string MonthlySalary { get; set; }
        public Nullable<int> IDDepartmentEmpl { get; set; }
    
        public virtual DepartmentEmpl DepartmentEmpl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesAndProduct> EmployeesAndProduct { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Post Post { get; set; }
    }
}
