//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocolateFabricApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinishedProducts()
        {
            this.EmployeesAndProduct = new HashSet<EmployeesAndProduct>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Count { get; set; }
        public Nullable<int> IDPeriod { get; set; }
        public System.DateTime DateProduction { get; set; }
        public Nullable<int> IDDepartmentProd { get; set; }
    
        public virtual DepartmentProd DepartmentProd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesAndProduct> EmployeesAndProduct { get; set; }
        public virtual Period Period { get; set; }
    }
}
