//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocolateFabricApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainTable
    {
        public int ID { get; set; }
        public Nullable<int> IDClientAndOrder { get; set; }
        public Nullable<int> IDSupply { get; set; }
        public Nullable<int> IDEmployeesAndProduct { get; set; }
    
        public virtual ClientAndOrder ClientAndOrder { get; set; }
        public virtual EmployeesAndProduct EmployeesAndProduct { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
