//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammProductsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string NameProduct { get; set; }
        public string Version { get; set; }
        public int IDType { get; set; }
        public string Firm { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int IDApplicationArea { get; set; }
        public int CostOfLicense { get; set; }
        public int QuantityDownoload { get; set; }
        public int IDUser { get; set; }
        public int IDService { get; set; }
    
        public virtual ApplicationArea ApplicationArea { get; set; }
        public virtual Service Service { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
        public virtual User User { get; set; }
    }
}
