//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeografiaApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID { get; set; }
        public string NameCountry { get; set; }
        public string Region { get; set; }
        public string Capital { get; set; }
        public string Square { get; set; }
        public string AdvancedOr { get; set; }
        public int IDNationality { get; set; }
        public int IDPopulation { get; set; }
    
        public virtual Nationality Nationality { get; set; }
        public virtual Population Population { get; set; }
    }
}
