//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proverka.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazine
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public int NumberOfEmployees { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> City { get; set; }
    
        public virtual CurrentCity CurrentCity { get; set; }
        public virtual TypeMagazine TypeMagazine { get; set; }
    }
}
