//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelhozApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public int ID { get; set; }
        public string NameCompany { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public string TypeOfProperty { get; set; }
        public string NumberOfEmployees { get; set; }
        public string MainTypeProduct { get; set; }
        public string AdvancedOr { get; set; }
        public int Price { get; set; }
        public string Comment { get; set; }
        public int IDSupply { get; set; }
        public int IDProducts { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
