//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardInfoPesonal
    {
        public int IDGuard { get; set; }
        public string RegAdress { get; set; }
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public Nullable<int> IDLicense { get; set; }
        public Nullable<int> IDGuardGun { get; set; }
        public Nullable<int> IDDivision { get; set; }
        public Nullable<int> IDSchedule { get; set; }
        public Nullable<int> IDObject { get; set; }
    
        public virtual GuardInfoGun GuardInfoGun { get; set; }
        public virtual License License { get; set; }
        public virtual Object Object { get; set; }
        public virtual Podrazdelenie Podrazdelenie { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
