//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dboBUDULAIEntities : DbContext
    {
        public dboBUDULAIEntities()
            : base("name=dboBUDULAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GuardInfoGun> GuardInfoGun { get; set; }
        public virtual DbSet<GuardInfoPesonal> GuardInfoPesonal { get; set; }
        public virtual DbSet<License> License { get; set; }
        public virtual DbSet<Object> Object { get; set; }
        public virtual DbSet<Podrazdelenie> Podrazdelenie { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<SignIn> SignIn { get; set; }
    }
}
