
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Geograf.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Country
{

    public int ID { get; set; }

    public string Title { get; set; }

    public string Region { get; set; }

    public string Capital { get; set; }

    public string Square { get; set; }

    public string Economy { get; set; }

    public int IDPopulation { get; set; }

    public int IDEthnic { get; set; }



    public virtual Ethnic Ethnic { get; set; }

    public virtual Population Population { get; set; }

}

}
