
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Geograf.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Ethnic
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ethnic()
    {

        this.Countries = new HashSet<Country>();

    }


    public int ID { get; set; }

    public int IDNationality { get; set; }

    public int IDLanguage { get; set; }

    public int TotalNumber { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Country> Countries { get; set; }

    public virtual Language Language { get; set; }

    public virtual Natinolity Natinolity { get; set; }

}

}
