//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAuthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.ConnectCompanies = new HashSet<ConnectCompany>();
        }
    
        public int ID { get; set; }
        public string NameCompany { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public string TypeOfPproperty { get; set; }
        public string QuantityOfEmployees { get; set; }
        public string MainTypeProduct { get; set; }
        public string AdvancedOr { get; set; }
        public string Price { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectCompany> ConnectCompanies { get; set; }
    }
}
