//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAuthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectCompany
    {
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> SupplyID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
