//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastryShopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAndOrder
    {
        public int ID { get; set; }
        public Nullable<int> ClientRegisterID { get; set; }
        public Nullable<int> OrderRegisterID { get; set; }
    
        public virtual ClientRegister ClientRegister { get; set; }
        public virtual OrderRegister OrderRegister { get; set; }
    }
}
