//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastryShopApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PastryShopdDBEntities : DbContext
    {
        public PastryShopdDBEntities()
            : base("name=PastryShopdDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientAndOrder> ClientAndOrder { get; set; }
        public virtual DbSet<ClientMoreInfo> ClientMoreInfo { get; set; }
        public virtual DbSet<ClientRegister> ClientRegister { get; set; }
        public virtual DbSet<OrderRegister> OrderRegister { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SignIn> SignIn { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
        public virtual DbSet<TypeProduct> TypeProduct { get; set; }
    }
}
